### ISSUE TITLE
Cycleway on a bridge is drawn under road and railway

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#108]
See here https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.79773/2.29670

**Comment by Phyks** [comment]
I would tend to think this is expected and the same for osm.org render actually, except the fact that the dotted lines make this less obvious.

When looking at the cycleway, it is a large segment with no indication at all that this is a bridge https://www.openstreetmap.org/way/365650471#map=19/48.79792/2.29662. This looks like incorrect tagging to me and the cycleway should be split at the bridge edges and tagged as a bridge.

This being said, I'm not sure about the best tagging scheme here since tagging the cycleway as a bridge could be seen as two different bridges (one for the road, one for the cycleway), whereas there is a single bridge in reality, with both ways.

**Comment by Florimondable** [comment]
My mistake I should have check the way.
So yes bridge=yes is needed on it, bridge means that the way go on a bridge not that it is the bridge, see https://wiki.openstreetmap.org/wiki/Key:bridge
