### ISSUE TITLE
Dash road surface is rendered over cycle track

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#136]
See there rue Tilsit https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.87447/2.29676

**Comment by Phyks** [comment]
This is happening because "Rue Tilsitt" has a [separate cycleway](https://www.openstreetmap.org/way/680311659) which is bidirectional and overflowing on top of the "Rue Tilsitt" (this is expected).

Somehow, it seems attachments are drawn separately, which means

1. first the "Rue Tilsitt" surface is drawn
2. the cycleway surface is drawn, overflowing on the "Rue Tilsitt"
3. the surface of the "Rue Tilsitt" is drawn, overflowing back on top of the cycleway

Not sure exactly why this is happening here. https://tilemill-project.github.io/tilemill/docs/guides/symbol-drawing-order/ has an enigmatic sentence at the very end

>  If you want to ensure lines are always below fills, use separate attachments.


http://gis.19327.n8.nabble.com/attachment/5340415/0/MapnikXMLDescription.pdf page 28 has some extra details

> StyleName Elements are listed in the order they are to be applied to each data source.  It should be noted that when you have more than one style and or data source, the precedence of what get rendered first and in what order can lead to unexpected results. Especially if the styles have overlapping rules and symbolizers.
> 
> Datasource Elements are listed in the order that you want them processed, remembering that all the listed StyleName Elements are processed against a Datasource before moving to the next source.

But there is no information of the order of rendering within a `DataSource`. 

Having https://github.com/cyclosm/cyclosm-cartocss-style/issues/141 and https://github.com/cyclosm/cyclosm-cartocss-style/issues/115, it could be tempting to put cycleways in a separate layer, but this would probably be an issue for tunnel (cycleways under a tunnel, typically here https://cyclosm.github.io/cyclosm-cartocss-style/example.html#18/48.84040/2.37496). Note that we cannot simply discard cycleways with `tunnel=yes` or we would discard the whole cycleway [here](https://www.openstreetmap.org/way/190666063).
