### ISSUE TITLE
Add churches, temples and religious buildings

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#164]

**Comment by Phyks** [comment]
What is the precise purpose here?

Is it for tourism only, in which case we'd probably rather filter these on the presence of `historic=building` or `heritage` key, isn't it?

Is it because they are usually open and provide a shelter? In this case, I guess we should render all the `amenity=place_of_worship` places.

Do we want a differentiated render per religion (see https://github.com/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss#L614-L645) or a generic icon such as https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/place_of_worship.svg is enough?

**Comment by Florimondable** [comment]
In Heidelberg I can't see if this building is a crepe restaurant or the big church of the city.
Religious buildings are easy to spot in a city and most of the time a place for tourism.
Differentiated is better I think, a church doesn't look like a buddist temple.

**Comment by Phyks** [comment]
Done. Here are a few pictures at Z16/Z17/Z18.

![Screenshot_2019-10-08 CyclOSM — Kosmtik](https://user-images.githubusercontent.com/3856586/66402670-86cee780-e9e5-11e9-94e9-b67dcfe5e6b5.png)
![Screenshot_2019-10-08 CyclOSM — Kosmtik(1)](https://user-images.githubusercontent.com/3856586/66402672-86cee780-e9e5-11e9-9168-524f3770a14b.png)
![Screenshot_2019-10-08 CyclOSM — Kosmtik(2)](https://user-images.githubusercontent.com/3856586/66402675-86cee780-e9e5-11e9-8ae0-db1c21ff7089.png)
![Uploading Screenshot_2019-10-08 CyclOSM — Kosmtik(3).png…]()
![Uploading Screenshot_2019-10-08 CyclOSM — Kosmtik(4).png…]()

**Comment by Phyks** [comment]
Done. Here are a few pictures at Z16/Z17/Z18.

![Screenshot_2019-10-08 CyclOSM — Kosmtik](https://user-images.githubusercontent.com/3856586/66402670-86cee780-e9e5-11e9-94e9-b67dcfe5e6b5.png)
![Screenshot_2019-10-08 CyclOSM — Kosmtik(1)](https://user-images.githubusercontent.com/3856586/66402672-86cee780-e9e5-11e9-9168-524f3770a14b.png)
![Screenshot_2019-10-08 CyclOSM — Kosmtik(2)](https://user-images.githubusercontent.com/3856586/66402675-86cee780-e9e5-11e9-8ae0-db1c21ff7089.png)
![Screenshot_2019-10-08 CyclOSM — Kosmtik(3)](https://user-images.githubusercontent.com/3856586/66402676-86cee780-e9e5-11e9-8e55-2bdfc237b3ec.png)
![Screenshot_2019-10-08 CyclOSM — Kosmtik(4)](https://user-images.githubusercontent.com/3856586/66402677-86cee780-e9e5-11e9-8fdf-9ed492714388.png)
