### ISSUE TITLE
Rework POIs

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#207]
Related to #64, #142 and #169.

* Once a list of POIs more or less fixed, we should rework the icons to have a uniform and coherent set of icons (sizes, styles).

* We should rework colors. The food shop (purple) and pharmacies (red) are too strong and attract too much the eye with respect to the POIs with a lot of added value (bicycle, drinking water, toilets etc). An idea is to desaturate it completely (no more colors) and put back colors on some very particular POIs we want to emphasize.

**Comment by quasart** [comment]
Here are my reflexions about POI display, nothing crazy but I hope it helps to clarify this rework.

I wrote them as categorization rules, from higher to lower priority (By "priority" I mean "should hide a less important one at the same place")

### 1) Bicycle-specific amenities



Ex: bicycle parking, bicycle location, repair.. as listed in https://wiki.openstreetmap.org/wiki/Bicycle#Facilities)

This category is the most important, icons should be readable and high-contrasted.
They have highest priority, and should be blue obviously.



### 2) Public transportation

Ex: metro, tramway and train station, airport

Important because they are common target destination, meeting point, and useful to localize yourself on the map. And some trains allow bike transportation.

I think they should have a unique color too (purple?) Maybe public bicycle sharing (like velib) should share the same color ?

Zoom level should be what we're used to : national network from medium zoom, urban network at high zoom. Icons becoming bigger and labeled when zooming in.



### 3) Amenities you're likely to use when cycling, even if not directly related to bicycle

Ex: drinking_water, public toilets, sport shops, shelters

Could be unsaturated green, like footway. They should be easy to spot because someday you will need to adapt your route to reach them.
Zoom level should depends on "how rare this amenity is, and how far are you ready to go for this ?"


### 4) Tourism POI

Ex of amenities: view point, picnic table, camping, tourism office
Ex of attractions: monument, castle, archaeological site, zoo, waterfall

I guess they should be highlighted because I assume many map readers are bicycle-touring. But not very important : Icons should not have flashy color (brown ?) and should be small.

Zoom level for attractions depends on how attractive it generally is.

Tag `tourism=attraction` (or `tourism=yes`) is used to know when a POI is touristic of not




### 5) All other useful POI

Of course, useless POI should be removed completely for readability.

I see two interesting use cases:
- services : restaurant, shop, hospital, pharmacy, museum, cinema, internet access, swimming pool, ATM...
- big entities used as references for orientation : windmill, light tower, peak, saddle, non-drinkable fountain, bunker, cross, cave, waterfall...

They have very low priority, but still good to display if there is nothing else at the same place, at least for orientation. For this reason, if they are visible from far they should appear from medium zoom.

They should be small gray icons


What do you think ?

**Comment by Phyks** [comment]
Wow, thanks for this very cool feedback! It's a very good starting point in my opinion (and I agree with most of the design ideas :).

> services : restaurant, shop, hospital, pharmacy, museum, cinema, internet access, swimming pool, ATM...

I see a question here with respect to hospital and pharmacy. So far, these are considered as "emergency" features (together with `healthcare=*` and `emergency=phone`) and rendered with the highest priority (and red, which is probably too eye catchy). Not sure whether we should keep it this way or not.

For the record, the current rendering order (in terms of priority, first ones hide the ones coming after) is:
1. Emergency: `healthcare=*`, `emergency=phone`, `amenity=hospital`, `amenity=pharmacy`
2. Secondary emergencies: `amenity=bicycle_repair_station`, `amenity=compressed_air`, `amenity=drinking_water`, `amenity=police`, `amenity=toilets`, `amenity=water_point`
3. Bike: `shop=bicycle`, `amenity=bicycle_rental`
4. Supermarkets: `shop=supermarket`
5. Convenience: `shop=convenience`, `shop=convenience;gas`
6. Food: `shop=*` (food related) or `amenity=bar`, `biergarten`, `cafe`, `fast_food`, `food_court`, `pub`, `restaurant`
7. Everything else

**Comment by quasart** [comment]
Good question about emergency features.

Maybe hospital areas could be yellow (like in OSM). Anyway hospital icons should be visible from medium zoom because they generally are big.

Emergency phones could be highlithed because I guess they are rare or limited to relatively desert area.

I don't what what's the best for pharmacies : they might be useful but they are very common in some cities. Maybe a very small green +

**Comment by Florimondable** [comment]
I guess we can close that one.
