### ISSUE TITLE
More mountain bike features

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#208]
This is a ticket reminder to create more precise tickets:

If CyclOSM is for every cyclist we should take care also to MTB users. For the moment we only have third surface quality road and MTB routes. It seems that there are others feature we could add.
May be some from https://openmtbmap.org/ ?
see http://mtbmap.cz/

**Comment by Dardy87** [comment]
OpenMtbMap are very good but pay attention: mtb purpose map could have a lot of features, depending on many factors like, incline, difficulty, surface, etc.
In my opinion first thing of a map is that need to be easily readable, I think that adding other features can make cyclosm unreadable.
Maybe  the bast way is make some fork starting from cyclosm, in order to have simple but really useful map instead of multipurpose but unreadable map.
In fact also mtbmaps are only for mtb rider, there are other renders for cycle maps (with differente layout if you use road bike or tourism bike).
What do you think about it?

**Comment by Florimondable** [comment]
I agree with @Dardy87 you we should take care of not adding feature that leads to an unreadable map. We have already lot of features.
I don't do MTB bike so I have no precise idea of what is needed on a map that sport that's the reason of this ticket. May be we miss a feature that is widely use for MTB. Ideas are welcome :)

**Comment by Dardy87** [comment]
Most useful data to render for mtb purpose are tags related to difficulty for both uphill and downhill.
A path too steep can't be ride uphill, but maybe is a good trail to ride downhill.
These tags are mtb:scale (for descend with value 0 to 6) and mtb:scale:uphill (for uphill, with value 0 to 5).
There are also other tags, like "mtb:scale:imba", dedicated to bike parks or "incline" to identify if a trail goes up or down (depending on the way direction).
Finally you can do some things with surfaces, you can understand that mixing all these tags there are a lot of style combination.

**Comment by Phyks** [comment]
> There are also other tags, like "mtb:scale:imba", dedicated to bike parks or "incline" to identify if a trail goes up or down (depending on the way direction).

We plan on restoring hillshades and elevation curves #157 so this might do the trick for this.

> These tags are mtb:scale (for descend with value 0 to 6) and mtb:scale:uphill (for uphill, with value 0 to 5).

Indeed, this might be worth having!

**Comment by Phyks** [comment]
> There are also other tags, like "mtb:scale:imba", dedicated to bike parks or "incline" to identify if a trail goes up or down (depending on the way direction).

We plan on restoring hillshades and elevation curves #157 so this might do the trick for this.

> These tags are mtb:scale (for descend with value 0 to 6) and mtb:scale:uphill (for uphill, with value 0 to 5).

Indeed, this might be worth having!

**Comment by andrewharvey** [comment]
> If CyclOSM is for every cyclist we should take care also to MTB users.

The counter point is that we should distinguish road bike cycle track from mountain bike tracks so road cyclists don't unexpectedly end up routing themselves down a double black diamond mountain bike track.

At the moment the only way to distinguish if a highway=cycleway is a mountain bike track or not is to check for mtb:*= tags.

**Comment by Phyks** [comment]
> At the moment the only way to distinguish if a highway=cycleway is a mountain bike track or not is to check for mtb:*= tags.

From the description in the wiki (https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway), I would always expect the cycleway to be fitted for any kind of bikes. I would probably a cycleway which is only a fit for mtb as a `highway=path`.

I see `highway=cycleway` + `mtb:scale=0|1` around, in which case the `mtb:scale` seems to be used only to reinforce the expected surface.

There are however some `highway=cycleway` which are only dedicated to MTB around there, such as https://www.openstreetmap.org/way/86978431#map=17/41.26426/-73.91907. There are only 835 such ways around the world, so isn't it a bad tagging and should be replaced by `highway=track`?

**Comment by andrewharvey** [comment]
> From the description in the wiki (https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway), I would always expect the cycleway to be fitted for any kind of bikes. I would probably a cycleway which is only a fit for mtb as a highway=path.

I don't think that's clear from the wiki, my assumption was that [highway=cycleway](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcycleway) was for any kind of path which was designated specifically for bicycles, and mountain bike tracks fit that description.

[highway=path](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath) is for a "generic path, either multi-use or unspecified usage", a mountain bike path is not that, since it's has a specific usage for bicycles.

On the tagging side, it's worth having this discussion but I don't think it's clear exactly from the wiki, but on the cycleosm side we should still try and do what we can based on the tags used, so regardless of the highway tag, mtb:scale>=1 or mtb:scale:imba>=1.

In my map style for https://www.beyondtracks.com/map/ I use a dark blue for mountain bike tracks and light blue for urban bike tracks, but not sure if this is the best styling.

> so isn't it a bad tagging and should be replaced by highway=track?

highway=track must be wide enough for a car, so any singletrack mountain bike track is definitely not highway=track.

**Comment by andrewharvey** [comment]
according to my overpass query, there are 3500 highway=cycleway's which indicate they are mountain bike tracks. That said, I'm not great at overpass queries so I might be wrong.

```
[out:csv(::count)][timeout:25];
(
  node["highway"="cycleway"]["mtb:scale"];
  way["highway"="cycleway"]["mtb:scale"];
  relation["highway"="cycleway"]["mtb:scale"];

  node["highway"="cycleway"]["mtb:scale:imba"];
  way["highway"="cycleway"]["mtb:scale:imba"];
  relation["highway"="cycleway"]["mtb:scale:imba"];
);
out count;
```

**Comment by Phyks** [comment]
> according to my overpass query, there are 3500 highway=cycleway's which indicate they are mountain bike tracks

That's similar to my results (I used our worldwide Postgis database). I simply ignored the `mtb:scale=0` and `mtb:scale=1` which (around me) are often used as a reinforcement of the surface tag (in complement with `gradtype`), without any real MTB meaning. That's why we have a different count.

> I don't think that's clear from the wiki

Indeed, this is never stated explicitly in the wiki. I was assuming it since there was no sign of MTB.

> On the tagging side, it's worth having this discussion

:+1: for this, we should clarify this point (and probably state explicitly in the wiki that cycle ways can be limited to a subclass of bikes, e.g. MTB). I'll post about this.

> but on the cycleosm side we should still try and do what we can based on the tags used

If the tagging is fully incorrect (e.g. if a cycleway should always be valid for any kind of bikes and not restricted to MTB for instance), I would rather not try to fix the tagging in CyclOSM (such as contributors can spot the tagging error). If the tagging scheme is valid, then, sure, we should do everything we could to render these tags nicely!

**Comment by Florimondable** [comment]
See #336 for next discussion of mtb:scale implementation

**Comment by Phyks** [comment]
Cycleways with `mtb:scale` are now rendered.

If I read correctly, the remaining issue is rendering `mtb:scale:uphill` (`mtb:scale` being only for descent?).

**Comment by Florimondable** [comment]
Yes and #341 
(I'd created an other ticket for that, and keeping this one for the general purpose).
