### ISSUE TITLE
Parking quality rendering

### ISSUE THREAD

**Issue by pau-a-velo** [cyclosm/cyclosm-cartocss-style#268]
Hi, parking is an important matter for people with costly bikes.
Some bike parkings do not fullfill the minimum requirement for security. 
`bicycle_parking: wall_loops`,` bicycle_parking: ground_slots`, `bicycle_parking:informal` ...
They are the one that are not supervised, and where it is not possible to lock the bike frame. Moreover, wall_loops tends to damage bike wheels.

You already have special icon for secured parking and covered parking, that can combine together (great job!). It would be very usefull if "unsecure" parkings rendered differently, maybe half-circle instead of full circle. I think it is more reliable to list what is a secured parking, than to list what is not a secured parking. So I propose here a list of what should have a full circle, other are suppose to only have a half circle 

full circle:

* ` bicycle_parking : stands`
* `bicycle_parking : rack`
* `bicycle_parking : bollard`
* `bicycle_parking :  lockers`
* `bicycle_parking :  wide-stands`
* `bicycle_parking : building`

half-circle: all other kinds of parking (a half circle can also be secured by a box or covered by o roof)

**Comment by Phyks** [comment]
Hi,

First, sorry for the late feedback on this issue...

>  Some bike parkings do not fullfill the minimum requirement for security.

Definitely agree! :)

> So I propose here a list of what should have a full circle, other are suppose to only have a half circle

I have mixed feelings about this segregation on `bicycle_parking` values. `bicycle_parking` key in itself is an issue since it is too subjective and not normalized at all: what would you consider a stand or a wide stand? wall_loop vs rack? what about well designed "wall_loop" with an associated stand? what is this https://help.openstreetmap.org/upfiles/bike_rack_wavy_SNBHtdV.jpg?

I would probably more enclined to do the opposite, with explicitly marking known bad quality as half circle.

@Florimondable what do you think about this topic?

**Comment by Florimondable** [comment]
We have more and more bicycle parking for dock less vehicles (electric scooters and bicycles) in Paris. We gonna need this requirement in order to distinguish between `floor` parking and `stand` ones.

**Comment by Phyks** [comment]
What about having the bicycle parking color purple for these parkings? This would be in sync with the bicycle rental amenity icon which is purple as well.

**Comment by Florimondable** [comment]
floor != to rent

**Comment by lamyseba** [comment]
Sorry, I think rendering `ground-slot` and `floor` is a good thing (good job!), but does not close the issue for me. People need a way to know where they will be able to lock the frame of their bicycle, not just the wheel.  Taking samples from https://wiki.openstreetmap.org/wiki/Key:bicycle_parking, at least `wall-loop` needs to be discriminated, with a dash or a half-circle, as you want.
Replying to Phyks (sorry for the delay), https://help.openstreetmap.org/upfiles/bike_rack_wavy_SNBHtdV.jpg is ok to lock the frame, and is not a `wall-loop`, so you can name it anything else than `wall-loop` (`rack` would be a good answer IMHO), it will render as a circle, meaning you can lock the frame of your bicycle.

**Comment by Florimondable** [comment]
Well yes there are different level of security :
1 - not lockable
2 - lockable by the wheel
3 - frame lockable
4 - inside a room
5 - supervised (can be combined with others)

Adding distinction of 2 (lockable by the wheels) is yet another complexity in the map.
I think knowing that you can lock or not the bike is the most important thing.

**Comment by lamyseba** [comment]
It seems to me that all bicycle organizations insist on the fact that not locking the frame is an insecure and bad practice. At least here it France, https://www.fub.fr/sites/fub/files/fub/Boutique/exposition_fub_marquage_antivols_bd.pdf,  but quite sure things are the same in European Union. https://thebestbikelock.com/how-to-lock-your-bike/
If cyclosm let users believe they will be ok with just locking the wheel, and that frame or no frame is not a problem, the map is promoting a quite bad practice.

Stealing of bikes is a real problem, discouraging lots of people to use their bike for everyday need. Because they fear their costly bike to be stolen, or because their bike was stolen and they just don't want to buy another one.

Moreover, lots of politic or technical people working for them are not very aware of "good practice" neither, and if the users do not remember them that cyclists need good parking quality, they often will go to the cheapest solution :  the wall loop. It seems to me cyclosm is a user map, and could play a role in promoting good parking practice, for the users, and for the politics/technical people.
