### ISSUE TITLE
Parking (or other bicycle POI) may be not be rendered

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#32]
There is some cases where a parking is not rendered, see :
https://tiles.phyks.me/#18/48.87731/2.36389
node https://www.openstreetmap.org/node/895608360#map=19/48.87745/2.36410&layers=C

I do think that every bicycle related POI should be always visible. It is more important than a road name, or a bus stop, or whatever. Hazard is not welcome here.

We have an example with the bicycle shop Bicycl'Art
https://tiles.phyks.me/#16/48.8824/2.3677
https://www.openstreetmap.org/node/3651262894#map=19/48.88220/2.36818&layers=C

**Comment by Phyks** [comment]
There is the same issue happening with police offices in Montrouge in https://tiles.phyks.me/#16/48.8175/2.3200 (compare with https://www.openstreetmap.org/#map=16/48.8175/2.3200).

In the case of police office, it is due to a conflict between the icon and the label of the road. Two solutions:

1. Either allow overlap between icon and road label
![1](https://user-images.githubusercontent.com/3856586/52443062-0a69c900-2b25-11e9-978b-f71b6c47df69.png)

2. Or hide icon or road label. We currently hide the icon, osm.org chooses to hide the road label.

What would be the best option in your opinion?

**Comment by Phyks** [comment]
In the link in the first post, same thing was happening I think. The bike parking is now displayed, but this is a coincidence I think. The nearby drinking water and toilets are hidden (drinking water conflicts with barrier, toilets don't fit with cycleway I think).

Should we allow overlaps? What should be the priorities? I would favor drinking water on barriers.

**Comment by Florimondable** [comment]
I'd say for a cycling map cycling POIs are more important than every other stuff.
Parking overlapping road name could be ok, for other POIs I don't think so.

If osm.org choose to prefer POI over road name I think it is for a good reason, don't know why

**Comment by Phyks** [comment]
I pushed a fix today, and tiles have been updated on tiles.phyks.me.

> There is the same issue happening with police offices in Montrouge in https://tiles.phyks.me/#16/48.8175/2.3200 (compare with https://www.openstreetmap.org/#map=16/48.8175/2.3200).

This is now fixed.


> We have an example with the bicycle shop Bicycl'Art

I think I know where this is coming from, I'll try to fix it this weekend.


> There is some cases where a parking is not rendered, see https://tiles.phyks.me/#18/48.87731/2.36389

The only remaining issue there is the drinking water being hidden by the barrier. Not sure which one should have priority here? Probably the drinking water though.

**Comment by Florimondable** [comment]
Great!
Drinking water first, first aid first.

**Comment by Phyks** [comment]
Should be fixed now. I'll regenerate the tiles later today.
