### ISSUE TITLE
Updates are vert slow (Days)

### ISSUE THREAD

**Issue by BoffII** [cyclosm/cyclosm-cartocss-style#358]
Updates use to take only a few minutes to show on maps...nos It take days

**Comment by Florimondable** [comment]
Hi, yes it seems that our render system doesn't render anymore modification since first may, see https://munin.openstreetmap.fr/static/dynazoom.html?cgiurl_graph=/munin-cgi/munin-cgi-graph&plugin_name=osm11.openstreetmap.fr/osm166.openstreetmap.fr/renderd_zoom_time&size_x=800&size_y=400&start_epoch=1585841577&stop_epoch=1588692777

We'll try to solve this soon.

**Comment by Phyks** [comment]
We had a bug on the server and outdated tiles were no longer expired. This is now fixed but might take some time to catch up (~ 7 days at max before everything is expired).
