### ISSUE TITLE
Bike station icon is hidden by lower importance amenities

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#360]
see Pierre Demours-Laugier at z17
https://www.cyclosm.org/#map=18/48.88115/2.29495/cyclosm

**Comment by Phyks** [comment]
Contrary to what we could think at first sight, the bicycle icon is actually not hidden by the fast food, but by the pharmacy.

We cannot do much here, except eventually invert the precedence.

**Comment by Phyks** [comment]
I reworked the order in https://github.com/cyclosm/cyclosm-cartocss-style/commit/9d992b4b5733694f5dd6d879d3dc4dbc752ffb80 to draw:
* First, pure bicycle POIs
* Then heatlhcare / emergency icons
* Then the rest

Reasoning behind this is that CyclOSM is first and foremost a bicycle map (so should draw bicycle features as much as possible) and that the cases where conflicts would arise are inside cities, where there is enough healthcare / emergency / pharmacy services nearby so that not showing a single one at some zoom levels should not be an issue.
