### ISSUE TITLE
Rendering of service subtypes with thinner lines

### ISSUE THREAD

**Issue by Martin868** [cyclosm/cyclosm-cartocss-style#372]
As it is done by the standard openstreetmap.org rendering engine, would be great that the highway=service with a service=(driveway, drive-through, parking_aisle) be rendered with a line that is much thinner than the default highway=service road. In particular driveway going to private houses and parking lot aisle wound be distinguishable and yet much less dominant in the map. The current rendering make no distinction and in many areas where the thinner subtypes are being used it is not very readable. # #

**Comment by Florimondable** [comment]
Yep, link with #162

**Comment by quasart** [comment]
Here is a try, I made them visible only from z16, and thinner, a bit like in osm-carto :

![z15](https://user-images.githubusercontent.com/3080387/94725897-c57b5180-035c-11eb-9306-9970fc8903d3.png)
![z16](https://user-images.githubusercontent.com/3080387/94725902-c7ddab80-035c-11eb-9c29-7ee022e68430.png)
![z18](https://user-images.githubusercontent.com/3080387/94725914-c9a76f00-035c-11eb-92a3-52c0f548244c.png)
![z17](https://user-images.githubusercontent.com/3080387/94725915-cad89c00-035c-11eb-8679-cf0e876c6de1.png)

**Comment by Florimondable** [comment]
Every road and path are rendered from Z11, it should be the same for service subtype road

**Comment by quasart** [comment]
Hello,

Why do you think it have to be that way ?

minor service roads are always short and I feel like seeing them at low zoom is only disturbing, taking focus over classic ways, hiding general structure of the neighbourhood shapes. 

In default osm carto, even major service roads are hidden below s14. 

Have you ever plan your route through a minor service road at low zoom ?

At least, parkings alleys are definitely useless At low zoom because aera polygon is rendered anyway.

**Comment by Phyks** [comment]
> At least, parkings alleys are definitely useless At low zoom because aera polygon is rendered anyway.

Note that we are currently missing the area polygon for parkings and we should work on it. See https://github.com/cyclosm/cyclosm-cartocss-style/issues/162.

**Comment by quasart** [comment]
Why do you think it have to be that way ?

minor service roads are always short and I feel like seeing them at low zoom is only disturbing, taking focus over classic ways, hiding general structure of the neighbourhood shapes.

In default osm carto, even major service roads are hidden below s14.

Have you ever plan your route through a minor service road at low zoom ?

At least, parkings alleys are definitely useless At low zoom because aera polygon is rendered anyway.


Le 3 oct. 2020 à 18:29, Florimondable <notifications@github.com> a écrit :

﻿

Every road and path are rendered from Z11, it should be the same for service subtype road

**Comment by quasart** [comment]
> Note that we are currently missing the area polygon for parkings and we should work on it. See #162.

parking polygons look rendered in `base.mss`.
I see no issue about polygon in #162, only 'P' icon and roads color.

**Comment by Phyks** [comment]
Indeed, my bad, we are just missing the icon. I was thinking we were missing the full parking rendering.

**Comment by quasart** [comment]
Reading wiki documentation of these minor service roads again, I think that if you need to see them at mid-zoom (z11-z15), it must be bad tagging.

I find this image in wiki documentation pretty clear : https://wiki.openstreetmap.org/wiki/File:Parking_bad_example.png
![](https://wiki.openstreetmap.org/w/images/2/2f/Parking_bad_example.png)
