### ISSUE TITLE
Path as more visible

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#387]
I'm not satisfied with path rendering they are not visible enough, they doesn't invite cycliste to ride over them while there can be cycle.

**Comment by nsomlai** [comment]
Check out the Hungarian (now abandoned) site: https://merretekerjek.hu/#zoom=11&lat=46.359&lon=20.0459&scope=varosban

Maybe it gives some ideas to render more visible pathways. It focuses mainly on infrastructure because we do not have many cycling networks (BTW I strongly agree that routes should be on a layer to be able to switch them off) and even an Eurovelo route can go through a dirt road.

**Comment by Phyks** [comment]
Merging with #401.
