### ISSUE TITLE
cycleway=share_busway & oneway=yes rendering issue

### ISSUE THREAD

**Issue by SupaplexOSM** [cyclosm/cyclosm-cartocss-style#394]
On ways with "cycleway=share_busway" and "oneway=yes", the cycleway should only be rendered on one side (right side). Currently, it's drawn on both. "cycleway:right" is more specific, but if only "cycleway" is specified on oneway ways, this should be assumed as the default. For contra flow cases there is "cycleway=opposite_share_busway".

**Comment by Phyks** [comment]
Hi,

It is definitely wrong to assume a `cycleway=share_busway` is on the right side. This is usually true countries with right-hand traffic. This is almost always wrong in countries with left-hand traffic.

Even in countries with right-hand traffic, it is sometimes wrong and the `cycleway=share_busway` is actually a `cycleway:left=share_busway`.

From OSM wiki, `cycleway=share_busway` tag is

>     A special lane reserved for public transport on which cyclists are also allowed to bike.

Note that there is absolutely no indication on the side.

`cycleway:left/right` is usually the best tagging practice since it gives the full information in an exploitable form. About this, see the doc about the `cycleway=opposite_share_busway` tag:

> Consider using the cycleway:left=opposite_share_busway or cycleway:right=opposite_share_busway tags instead, as this describes on which side the contraflow shared bus lane is.



Long story short, there is basically no way to know on which side should lie any `cycleway` value. Hence, CyclOSM decides to render them on both side and to promote a better tagging scheme (left/right) which helps cyclists realize the potential discontinuities in the network.
