### ISSUE TITLE
path colors

### ISSUE THREAD

**Issue by quasart** [cyclosm/cyclosm-cartocss-style#401]
Hello Cyclosm !

I try to understand path rendering.

Reading the legend, I'm expecting :
* Blue is cycleway (track where cycling should be nice and obvious).
* Cyan is `bicycle=designated` but not fully a cycleway (This one is not that simple to understand). De facto it's rendering of path made for cycling but shared with pedestrian (not segregated).
* Green is general purpose path (open to bikes but not made for them).
* Brown is footway/bridleway (path exists, but you should not ride there).
* Dark blue is a track (something like a general purpose path, but large).

I have some questions, because we meet many tag combinaisons in OSM database :

1. `highway=cycleway foot=yes/designated` is rendered blue. I thought it's bad tagging to have pedestrian on a cycleway, but this is allowed [here](https://wiki.openstreetmap.org/wiki/Tag:bicycle=designated), and it's common to describe French "voie verte".
Don't you think it should be rendered like a `highway=path/footway bicycle=designated` ? Blue cycleway with a footway border when `segregated=yes`, Cyan otherwise.

2. About this footway border, it's rendered in green today. It should have changed to brown like footway did. Am I wrong ?

3. `highway=path bicycle=no` is rendered in gray, making them hardly visible in parks. But this tagging sounds like footway. Don't you think all public footways should be rendered the same way for consistency ?

4. `highway=track` is dark blue, very close to cycleway color. In my opinion, it should look more green, somehow like general purpose path. What do you think ?

5. `highway=track bicycle=designated` could be rendered in cyan like any designated path, no ?

Cheers

**Comment by Florimondable** [comment]
1. no, a cycleway is the best infra for cyclist even if there is sometime pedestrian on it
2. where ?
3. path are not footway (even with bicycle=no)
4. for me the two blue are not close (but that depend of people), may be more like a path, the point with track is that they should not have much trafic sinc it's for agricultural or forestry, that why it's more blue.
5. no track can have motor vehicle not path, they should have blue arrows as we already do on other roads.

**Comment by quasart** [comment]
2. An example there : https://www.cyclosm.org/#map=19/48.87389/2.23633/cyclosm

3. Slightly different in OSM datamodel documentation. But today `highway=path access=no` and `highway=path bicycle=no` are rendered the same way. From a cyclist point of view : you can dismount and walk in the second case, not the first. Rendering foot-only path like footway is an acceptable and understandable simplification IMHO

**Comment by brainwad** [comment]
Re: 3) I agree - the default bicycle access level is no in many countries for footpaths. So there shouldn't really be any difference between `highway=footway`, `highway=footway bicycle=dismount` or `highway=footway bicycle=no`, and I would colour them all brown. Currently the rendering is weird because only a few arbitrary footways have bicycle=no tags, even though legally they are all equivalent and only a bicycle=yes or bicycle=designated changes their status.

Re: 5) While it's true, shouldn't there be some way to distinguish tracks where bicycles are merely allowed from those tracks that are explicitly signed for bicycles (as opposed to e.g. just restricting motor vehicles to `destination/agricultural/forestry`).

**Comment by Florimondable** [comment]
3. Many people use footway where it’s a path, or when they think bicycle are not allowed. A bicycle=no means there is something on the ground stating that bicycle is forbidden, it’s explicit, it’s much stronger than just a footway.

5. Yes, they need to have also the "designated blue arrows" rendered

**Comment by brainwad** [comment]
I find, contrarily, that most bicycle=no tags on footpaths are not
accompanied by any special signs, but are just tagged by mappers who like
to specify all details instead of relying on the defaults (this style is
especially popular with highway=path). At least in countries where
highway=footway implies bicycle=no, there is rarely a meaningful
difference. And even when there is a meaningful difference, it is of course
allowed to use the path by walking the bike, so I think brown is a better
colour than grey, which is illegible and should be reserved for roads where
both riding and walking a bicycle are banned, e.g. motorways, and which
therefore "don't exist" in the mind of a cyclist.

**Comment by brainwad** [comment]
I think the blue arrows may not be legible on the dark blue track lines? Maybe tracks should be by default a less-blue colour (dark green?) and then bicycle=designated can be the current colour?

**Comment by quasart** [comment]
I obviously agree with brainwad : I met the same strange rendering in parks where some paths `highway=footway`, `highway=footway bicycle=no`, `path=footway bicycle=no`. A map of a park where most of the footway are hidden is hard to read, and makes hard to find out where I am.

Hidding `highway=footway bicycle=no` and not `highway=footway` sounds very surprising to me. Maybe because I see Cyclosm as a "green" map more than a cycle map.

**Comment by brainwad** [comment]
Re original point #4: After more use of the map, I continue to find `highway=track` very hard to distinguish from `highway=cycleway` - the colours are almost the same. I think it would make more sense if it was green, as `highway=path` is, for a couple of reasons:

1. The blue-er the line currently, the more bicycle-friendly/dedicated, e.g. dedicated cycleway is a darker blue than shared cycleway. `highway=track` breaks this by being an even darker shade of blue, but not being dedicated to bicycles and in some cases even permitting cars/trucks/tractors.

2. `highway=track` is basically a middle form between `highway=path`, which is green, and `highway=service`, which is either white or green depending on motor-vehicle permission. All three are not explicitly designated for bikes, and allow all forms of vehicle which will fit, varying essentially only in width and surface condition. So it would make sense that tracks were also a shade of green, probably slightly lighter than a path, but slightly darker than a no-car service-road - in a similar relationship as the dedicated vs shared cycleways are coloured.

**Comment by Phyks** [comment]
Is it still an issue with latest status of master branch?

**Comment by quasart** [comment]
Some points are still there (footway outine, cycleway with pedestrians) but this thread is more like a discussion about color philosophy that an actual issue. Feel free to close it

**Comment by Phyks** [comment]
Thanks for the feedback. I'm trying to limit the inflation of issues, therefore I'm closing it. But, please, do open new tickets on specific points that might still be bothering if you think this is worth an improvement.

I'll do a pass on the stalled PR as well ASAP.
