### ISSUE TITLE
[suggestions] Add marker ; Merge "Edit the map" buttons

### ISSUE THREAD

**Issue by Shohreh** [cyclosm/cyclosm-cartocss-style#419]
Hello,

1. I suggest adding a marker like on the OSM.org site. Pretty useful to show a location

2. Merge the two "Edit the map" buttons:
![image](https://user-images.githubusercontent.com/1541861/89710696-990f0e80-d985-11ea-807f-73a1004f0232.png)

Cheers,

**Comment by Phyks** [comment]
What is the "marker like on osm.org site"?

The two "edit the map" buttons are a bad copy/paste, this is fixed in https://github.com/cyclosm/cyclosm-website/commit/a6ee4d83fcb6634d9340930a894947379956fea8. Will be deployed at next version.

Note that these issues belong to the website (https://github.com/cyclosm/cyclosm-website) not the CartoCSS style.
