### ISSUE TITLE
Ford mapped as line

### ISSUE THREAD

**Issue by majkaz** [cyclosm/cyclosm-cartocss-style#424]
It would be nice to have the ford icon in the middle of a line, where ford is mapped such way (not just as point).

Compare [cycleosm](https://www.cyclosm.org/#map=19/48.99990/14.83843/cyclosm) with Carto.

**Comment by Phyks** [comment]
Fixed by now, we were lacking a render for open lines amenities (only `highway=ford` should be concerned so far.

Render is 
![2020-09-08-091044](https://user-images.githubusercontent.com/3856586/92444630-786beb80-f1b3-11ea-954a-2417bf4e1889.png)

This is affected by the same issue as #399, we'll rework them later and be tracking this in issue #399.
