### ISSUE TITLE
highway=living street not rendered, but in legend

### ISSUE THREAD

**Issue by majkaz** [cyclosm/cyclosm-cartocss-style#428]
Is this a bug?
As mentioned, the legend shows living street as light green color, but it is not rendered.

Example cyclosm live: 
https://www.cyclosm.org/#map=19/49.00084/14.54074/cyclosm_live
carto shows the living streets at the same place in light gray:
https://www.cyclosm.org/#map=19/49.00084/14.54074/openstreetmap

**Comment by Phyks** [comment]
Indeed, it should appear green only if this is a `maxspeed=20` living street. General case would make it look like a standard residential road (except for the casing).

There is https://github.com/cyclosm/cyclosm-cartocss-style/issues/238 about this question of implicitly rendering such a maxspeed value in a living street. This is however difficult to do in practice since every country has a different legislation on this matter and taking them into account in the style is quite consuming.

We definitely have at least to update the legend here. Not sure if we should update the style as well to emphasize the difference between living street and residential further? 

In France it seems quite common to tag the maxspeed value explicitly (although wiki is against it https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street), about 1/3 of living_street have an explicit maxspeed value: https://taginfo.openstreetmap.fr/tags/highway=living_street#combinations. The situation is very different on a global scale, with only 8% worldwide https://taginfo.openstreetmap.org/tags/highway=living_street#combinations.

**Comment by Phyks** [comment]
Closing this one in favor of #238.
