### ISSUE TITLE
Style for smoothness=intermediate

### ISSUE THREAD

**Issue by nsomlai** [cyclosm/cyclosm-cartocss-style#444]
Please add another dashing style or extend the current 'cyclocross' style to include intermediate smoothness. We road bike/recumbent riders would be very happy.

**Comment by Phyks** [comment]
From the wiki page about `smoothness` and the visual provided, I would expect a `smoothness=intermediate` way to be passable (even if not very fun) with a road bike and definitely passable with a recumbent bike or a regular bike (just standard tires, not road thin ones). Hence, I would not expect any surface dashing on these.

Am I missing something? Otherwise, would you have examples where the tagging is correct and the real situation is not the one on the wiki picture?

Thanks!

**Comment by nsomlai** [comment]
It's a matter of interpretation, I guess. Some of us want fun, not just being able to pass. :) Also, these roads can take quite a lot of extra energy because of the increased rolling resistance. When designing a 150-200 km tour for a day, it's good to know them, and avoid them if possible. That's what an extra style would help with.

In my country we also mark cycling roads that are mostly smoothly paved but have a lot of pavement errors (roots, cracks, potholes) with `smoothness=intermediate`. I know it's not ideal, but OSM has no other tag to specify road quality.

**Comment by Phyks** [comment]
I had a deeper look at this intermediate smoothness. From the images I see, it seems to be definitely passable with a road bike (I mostly see pavement errors or bad pavement, which in the end is far better than https://en.wikipedia.org/wiki/Paris%E2%80%93Roubaix#History_of_the_cobbles :). So I definitely would not add it to cyclocross style, as there is a huge difference between these and real cyclocross-only ways.

Regarding adding an extra dashing style, we already have two, and making the difference between them can sometimes get tricky.

In the end, I fear that adding a dedicated render for intermediate smoothness would induce confusion, especially for newcomers to the CyclOSM map, instead of really improving a situation which seems quite ok to me at the moment.

If anyone has an alternative render idea on this one, please feel free to discuss it!
