### ISSUE TITLE
Suggestion: render cycleways with shared way colour if inline_skates=yes

### ISSUE THREAD

**Issue by DerDings** [cyclosm/cyclosm-cartocss-style#484]
Skaters, like pedestrians, may share a path with cyclists. This requires additional mindfulness and probably a lower speed.

There is already a light blue colour for ways shared with pedestrians. The Idea is to apply the same colour on cycleways shared with skaters.

This may be tagged as [`inline_skates`](https://wiki.openstreetmap.org/wiki/Key:inline_skates)`=yes|designated|official`.
It does not apply if `segregated=yes` is given.

Example: https://www.cyclosm.org/#map=19/51.43783/7.27837
![image](https://user-images.githubusercontent.com/42044179/103468172-caceaa80-4d56-11eb-9654-61022c3be839.jpg)

**Comment by Phyks** [comment]
taginfo knows about 2k occurrences of this tag for `yes` value. This one is worth rendering I think. We might include `designated` as well.

`official` is unknown by taginfo, I'd drop it.

https://taginfo.openstreetmap.org/keys/inline_skates#values

**Comment by Phyks** [comment]
At the moment, we always consider a highway=cycleway is "designated" for bicycle, and any sharing implies a segregated=yes tag. Otherwise, we expect the highway=cycleway to be tagged otherwise, such as highway=path.

Hence, it is expected in the above example that no distinction would be made, even if `inline_skates` was taken into account by CyclOSM.

For other values of highway tag (highwway=path for instance) we consider by default that the way is shared, unless an explicit segregated=yes is present. Hence, the current rendering would be fine, even without taking into account `inline_skates` tag.


So, in the end and TLDR, this issue boils down to https://github.com/cyclosm/cyclosm-cartocss-style/issues/397.
