### ISSUE TITLE
15mph speed limit

### ISSUE THREAD

**Issue by pjr10th** [cyclosm/cyclosm-cartocss-style#512]
Hello,

I was wondering if 15 mph speed limits could be marked in the same way as 20 km/h speed limits rather than 30 km/h since they are closer to 20 km/h than 30 km/h numerically, and the purpose of such streets is generally to introduce a shared space scheme and bring motorists down to cycle friendly speeds.

We have a large network of 15 mph roads near me (possibly one of the largest in the world, considering the UK doesn't have them and I'm not sure if the US has 15 mph speed limits in such a way) which are designed to bring motorists using the roads down to pedal speeds to make it safer for cyclists. Having more distinction between these routes would make it clearer for cyclists using CyclOSM which routes are 15 and which 20.

**Comment by Florimondable** [comment]
Do you have examples where 15mph limit is applied ?

15mph = 24km/h

Actually a 20km/h limit is not very cyclist friendly, since half of the cyclist ride under this limit and an other half over (approximately), so the speed limit cyclefriendly is more the current for 30km/h. That's why 30km/h is blue (cycle color), and 20km/h more green (pedestrian friendly).
