### ISSUE TITLE
Draw military area

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#53]
https://tiles.phyks.me/#18/48.86883/2.36411

**Comment by Phyks** [comment]
Same thing [here](https://cyclosm.github.io/cyclosm-cartocss-style/example.html#16/45.7940/3.1292).

**Comment by sylvainavelo** [comment]
What's the point ?
Drawing the first one is useless, because there are no streets inside the area.
And the useful info on the second one is that the streets inside are not accessible. So perhaps the solution would be a specific rendering of the roads themselves.

**Comment by Phyks** [comment]
First one is probably just interesting for local knowledge (if you live nearby, maybe you can find your location more easily by looking for the military area).

Second one is indeed needed for the road access, same thing for https://cyclosm.github.io/cyclosm-cartocss-style/example.html#16/48.8074/2.3214 (these roads cannot be shortcuts, you cannot enter).

These examples are however not the most useful. In my opinion, military areas have to be drawn as areas, because of cases such as https://www.openstreetmap.org/way/378174285#map=12/47.0086/2.6518. This impacts a large area and is definitely needed to know if you are looking for some place to camp.

**Comment by Florimondable** [comment]
Yep, first reason is camping.

**Comment by sylvainavelo** [comment]
Ok so a simple rendering like the one on the default OSM rendering should be enough.

**Comment by Phyks** [comment]
![Capture d’écran 2019-06-05 à 16 12 38](https://user-images.githubusercontent.com/3856586/58963143-f1a8b180-87ac-11e9-9878-9e6b5aead028.png)
![Capture d’écran 2019-06-05 à 16 12 42](https://user-images.githubusercontent.com/3856586/58963146-f1a8b180-87ac-11e9-9571-d2f62a2c7bdb.png)
![Capture d’écran 2019-06-05 à 16 13 16](https://user-images.githubusercontent.com/3856586/58963148-f1a8b180-87ac-11e9-8431-9821af968b84.png)

I simply rendered it with a red background (red = danger / no access). I think this is enough, but we can probably have a more refined render if you think it deserves it.

**Comment by Florimondable** [comment]
Nice, I like the hatched rendering of osm.org.
And I just that there is two type dependings of the tag military :
https://www.openstreetmap.org/way/42018542#map=15/49.5610/3.9092
https://www.openstreetmap.org/way/282571866#map=13/49.5573/3.9360

**Comment by sylvainavelo** [comment]
Any refined rendering is a matter of taste but yes the osm.org default rendering with a lighter red and hatching is nice. And it shows an outline, which makes sense because there probably is a fence, wall or any kind of physical limit around such areas.

**Comment by Phyks** [comment]
@Florimondable Actually, this is a very nice trick, their `military` landuse is simply an overlay. So on true military parts, it appears red + hatched and in the forest it turns the forest landuse a bit more red.

![military](https://user-images.githubusercontent.com/3856586/61525941-b939fb80-aa19-11e9-9097-586b71ba8c77.png)

Fixed, looks like this now.
