### ISSUE TITLE
International cycling routes are not displayed correctly on z=4

### ISSUE THREAD

**Issue by hiddewie** [cyclosm/cyclosm-cartocss-style#530]
Compare the view https://www.openstreetmap.org/#map=4/44.96/-0.18&layers=Y and https://cycling.waymarkedtrails.org/#?map=4!47.0456!6.992.

Notice, that in The Netherlands, no international cycling routes are displayed, while they certainly exist. For example the North Sea Route EuroVelo 12, https://cycling.waymarkedtrails.org/#route?id=1977662&map=9!52.401!5.2951.

**Comment by Phyks** [comment]
The only such one is EV12 as far as I can see, and it is because this one is a superroute (a relation of relations). Related to https://github.com/cyclosm/cyclosm-cartocss-style/issues/221#issuecomment-607475734, superroutes, by design, are really difficult to render without using some tricks.

This is not an issue in most cases since the underlying relations are rendered. This is however an issue at Z4 since the underlying relations are mostly ncn and not icn.

Currently, I don't see any practical mean of handling these ones without pre-processing.

**Comment by hiddewie** [comment]
Yes, I understand. Indeed unfortunately the child relations themselves are ncn and not icn.

It would be nice to query the `route` relations with a nested subquery that traverses (child) relations. But that is difficult to implement. 

I will close this issue because it is not really a bug. Feel free to re-open it if you want to implement the preprocessing or the nested subqueries.
