### ISSUE TITLE
Qgis : add cyclosm with tool XYZ Tile Layers 

### ISSUE THREAD

**Issue by MathiasVadot** [cyclosm/cyclosm-cartocss-style#543]
In Qgis, it's impossible to add cyclosm's basemaps with the tool XYZ Tile Layers, let's see this tutoriel : https://www.spatialbias.com/2018/02/qgis-3.0-xyz-tile-layers/
It's there a problem with the tile server url https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png, or this use is not conforme to the license ?

**Comment by Phyks** [comment]
Hi Mathias,

It is likely QGis does not support {s} parameter in URL. You can replace it by any value a, b or c. 

For instance:
https://a.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png

Best,

**Comment by MathiasVadot** [comment]
Hi, thanks you it's work perfectly, good to know !
Mathias

**Comment by IndigoWizard** [comment]
That worked nicely!
Now as I used it as basemap i had a small issue, I'll post solution here since it's the main reason I wanted to use CyclOSM in qgis in the first place.

### Problem
Trying to use CyclOSM as basemap for QGIS layout print results in infinite load then time out.

### solution
web map > QuickMapServices plugin > Settings > Tiles > Tiles download timeout (ms*) > change it from 60000 to 100000.

This will allow CyclOSM to have enough time load it's tiles in the print layout.

### visual
![image](https://user-images.githubusercontent.com/43890965/181937827-c58ace62-3bee-4aec-8df9-e28060a63970.png)
