### ISSUE TITLE
rooftop parks are not visible

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#547]
### Issue
Currently, areas with leisure=park are shown in green. If they are located above à building, parks are visible up to zoom level 15 and disappear from zoom level 16 when buildings become visible.
zoom level 15 :
![image](https://user-images.githubusercontent.com/8955390/113593926-4c282880-9637-11eb-9962-d39095237d2f.png)

zoom level 18
![image](https://user-images.githubusercontent.com/8955390/113594036-6c57e780-9637-11eb-9f81-081df24c0ccc.png)
only the part of the park which is not above the building (but above empty space) remains visible in green.

### Solution
Parks should always be shown in green even on top of a building

https://www.cyclosm.org/#map=17/48.81089/2.32879/cyclosm

**Comment by quasart** [comment]
Hello,
This solution would hide many small buildings under big parks 😕

**Comment by Phyks** [comment]
I don't see any good solution for this particular case without investing tons of effort into rendering layered objects. Plus for a cyclist, current behavior is probably more useful than having amenities hidden below park (they are likely more interested into the shops inside the mall rather than by the park on the rooftop, which is probably not even accessible by bike).

Even the osm.org render is quite a mess there https://www.openstreetmap.org/#map=18/48.81114/2.32913

**Comment by patman37** [comment]
I understand it could be tricky to handle the layers, but amenities could still be visible even in green colour

**Comment by Phyks** [comment]
Having looked again at this issue, I don't see any fix that would both work at scale and convey the correct meaning. OpenStreetMap-Carto render is not better here, and even very local renders have the same issue https://osmontrouge.fr/@48.811284,2.328337,17.34.

The only fix I can see is to move to a fully layered / or indoor render https://osmontrouge.fr/3d=@48.810715,2.328139,18.12. Not really something easy and worth doing in CyclOSM.

Therefore, I'm closing it.
