### ISSUE TITLE
Rework colors of cycle routes / overlapping cycle routes

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#55]
Currently cycle routes are:

- Green for international routes
- Red for national ones
- Purple for regional ones
- Blue for local ones

This is mostly based on the OpenCycleMap design choices. They might not be optimal:

* EuroVelo roads have multiple colors (https://en.wikipedia.org/wiki/EuroVelo) so any color is probably fine for international routes.
* Regional and local ones probably differ a lot based on the area, so same, any color is probably fine. Blue and purple is close to the blue color we use everywhere else to indicate cyclability, so should be fine.

However, concerning the national ones, they are usually "voies vertes" in France and the whole communication about them uses the green color https://www.af3v.org/. So red is probably not a good idea for them. Another concern is that red is very far from blue (which indicates cyclability) in the color spectrum and too close to yellow/orange which we use for major highways (which we might want to avoid with a bike).

This is valid for France, of course, but might not for other countries. It seems Germany actually uses red for bike-related stuff https://en.wikipedia.org/wiki/German_Cycling_Network#/media/File:D-Netz-Route,_Abschnitt_K%C3%B6ln-Poll_,_Rheinaufw%C3%A4rts.jpg.

**Comment by Florimondable** [comment]
May be we can use the route's color when defined ?
https://wiki.openstreetmap.org/wiki/Key:colour

An other issue is the mixed color of different routes on the same portion of way.

**Comment by Phyks** [comment]
Also, blue for local bike route interferes quite easily with the blue from bike infrastructure. Maybe the color should differ more between infrastructure and routes.

**Comment by natolh** [comment]
This network distinction is done by OpenCycleMap, but, I don't see the point in it, what's the use case ? I mean when I plan a route I'm far more interested in the quality of the infrastructure (separated way, asphalt surface, good smoothness) than sticking to a particular network. But that's my own advice. I think this feature should be dropped and perhaps the colour filling of routes could be used for something else ? Surface perhaps ?

**Comment by Florimondable** [comment]
Many people use cycle routes for their holiday, for instance La Loire à Vélo is very crowded.
For myself when I travel I jump from country roads to cycle routes, to have the more efficient and calm route.

Nevertheless I agree with you @natolh infrastructure is the most important information, and in the actual state cycle route can hide infrastructure which is not desired.

**Comment by Florimondable** [comment]
May be the solution for color is to use only two colors, one color for local and regional, an other color for national and international (these colors could be little different like blue and light blue), when mixed local and regional will do the same color and local and national would do the national color.

**Comment by natolh** [comment]
I agree that some people follow specific routes for their holidays but they can still see references of such ways and perhaps, even better, use a router. I've never used them myself, but I think, like you say that the initial idea of rendering this networks differently is because international routes tend to be good quality infrastructure (which might not be always the case). But instead of taking this assumption maybe directly rendering type of infrastructure is better.

The only useful distinction between networks, in my own opinion, is that like primary roads for cars, international networks should be visible at low zoom levels and not national / regional networks.

**Comment by Phyks** [comment]
> because international routes tend to be good quality infrastructure (which might not be always the case)

From my own experience (biased towards France), the local and regional ones are usually not very good routes. They are usually coming from cycling as a sport and use a lot of shared (but rather calm) roads. National and international ones one the contrary tend to use more dedicated infrastructure. Many of the routes tend to overlap since international ones tend to build up on national infrastructure etc (I think there is even a proposal to map the fact that they share the same roads segments in OSM, through superroutes or something like this).

> May be the solution for color is to use only two colors, one color for local and regional, an other color for national and international (these colors could be little different like blue and light blue), when mixed local and regional will do the same color and local and national would do the national color.

There was a proposal to use the road color as well (https://wiki.openstreetmap.org/wiki/Key:colour). In my opinion, using the road color makes sense more than a color based on level of infrastructure: this is what can be seen on the field.

Also, blue is already used a lot for cycling-friendly stuff (maxspeed, infrastructure etc). Maybe routes should have a different color?

Anyways, :+1: for clustering into two groups only: local/regional (short distance, daily based) and national/international (long travel, holidays-like).

**Comment by natolh** [comment]
> From my own experience (biased towards France), the local and regional ones are usually not very good routes. They are usually coming from cycling as a sport and use a lot of shared (but rather calm) roads. National and international ones one the contrary tend to use more dedicated infrastructure.

So rendering roads based on their network memberships seems to be a mere substitute for infrastructure quality. Rendering infrastructure quality directly will simplify the maps.
And for those of us that are planning long distance trip and really want to stick to a particular network without using a cycling router, we can still render this long distance networks using the road color + ref at low/medium zoom level ? Using colors at low zoom level will not complexify the map because type of infrastructure / surface is not rendered. If the color of such routes should be kept at high zoom level perhaps color for the rest of the cycle network should be choosen wisely. For example, dark blue is already used by EuroVelo number 15.
To support my point, geovelo service is not rendering infrastructure differently depending on the membership to a particular network. But still offer the possibility to display at low zoom level international routes / long distance routes.

**Comment by Phyks** [comment]
This has been greatly improved with the latest work of @Florimondable I think. https://tiles.phyks.me/#12/48.8588/2.3470 is up to date with the latest version.

Overlapping cycle routes now render better. We should probably play a bit with `line-comp-op` property to avoid the overlay to be too dark.
