### ISSUE TITLE
Start and end of routes not visible.

### ISSUE THREAD

**Issue by joshinils** [cyclosm/cyclosm-cartocss-style#556]
I would like for the start and end of routes that there be some special markers that they end/start.

For example here: https://www.cyclosm.org/#map=20/52.58995/13.34794/cyclosm

There are multiple routes crossing, one is ending/starting and maybe one is changing direction? I really can't tell like this.
Most of them have the same colour and the little symbol on the way is only displayed further up the route, not at intersections.
I don't know why the Mauerweg-Route is purple or what that means. (what differentiates a Regional bike route from a Local bike route)
If multiple routes use the same way it is also hard to see which ones go where, again especially at an intersection.
Maybe the little symbol with the abbreviation and an arrow could signify wether the route goes straight, turns, or starts/stops could help, but only if necessary like here where there are other routes.

**Comment by Phyks** [comment]
See https://github.com/cyclosm/cyclosm-cartocss-style/issues/576, this is a high zoom level feature, and I am more inclined at the moment to simply remove the bicycle routes at this zoom level, since they are causing more troubles than helping. We would therefore defer bicycle route rendering to an overlay layer, Waymarked Trails for instance.

**Comment by joshinils** [comment]
ok, i think they are annoying too
