### ISSUE TITLE
Bad rendering of Relation 

### ISSUE THREAD

**Issue by pyrog** [cyclosm/cyclosm-cartocss-style#586]
Example: [relation 11010097](https://www.openstreetmap.org/relation/11010097) on [Waymarkedtrails](https://cycling.waymarkedtrails.org/#route?id=11010097&map=17!45.9044!6.1268), on [CyclOSM](https://www.cyclosm.org/#map=17/45.90392/6.12699/cyclosm)

<img width="33%" alt="Waymarkedtrails" src="https://user-images.githubusercontent.com/2158081/124357524-3ddcaf00-dc1c-11eb-961e-139310f1cf6f.png"> <img width="33%" alt="CyclOSM" src="https://user-images.githubusercontent.com/2158081/124357543-5b117d80-dc1c-11eb-9e1d-8a6065ab5abc.png">

**Comment by Phyks** [comment]
This relation is a superroute, which is not a scheme supported by CyclOSM. 

Osm2pgsql which is used for importing osm data into postgresql do not support them and it would require deviating too much from the standard osm2pgsql configuration to support them.

**Comment by pyrog** [comment]
😞 Huge vélo routes are usually super routes.

Please, keep this issue open until Osm2pgsql will support them 😉

**Comment by Florimondable** [comment]
Yeah, and that doesn't explain why we're having this artefact.

**Comment by Phyks** [comment]
Regarding superroutes, see https://github.com/cyclosm/cyclosm-cartocss-style/issues/221. This issue is stalled on osm2pgsql side and the child relations are already rendered (which means the full relation is actually correctly renderd in this particular case).

There is however an artifact on the rendering, sorry I was on my smartphone and missed it in your original post. The issue is actually coming from the child relation https://www.openstreetmap.org/relation/5341856 which is incorrectly rendered, I'm not sure why.

I'll dig further into this, but I have not found anything conclusive so far. My best guess is that the members of the route might not be correctly ordered, which might confuse osm2pgsql geometry algorithm.

**Comment by pyrog** [comment]
The relation is splitter in several pieces according r[elation analyser](http://ra.osmsurround.org/analyzeRelation?relationId=5341856&_noCache=on).

**Comment by matkoniecz** [comment]
Maybe ghost ways are caused by a osm2pgsql bug https://github.com/openstreetmap/osm2pgsql/issues/1394

https://lists.openstreetmap.org/pipermail/dev/2021-February/031048.html

> The error happens when there is a boundary relation containing exactly
> two ways forming a closed ring and the ways are oriented against each
> other. So they both have the same first and last nodes. The bug does
> not appear when the last node of one of the ways is the first node of
> the other. (Most likely the bug will also happen if there are four
> ways of which two create one ring and two another etc.)

> It is also possible to fix at least some of these cases by simply
> turning around one of the member ways. You can do this without the
> software having been updated. Just take care that turning around the
> way doesn't create other problems.

https://github.com/gravitystorm/openstreetmap-carto/issues/3822 is a very, very similar bug

Maybe here it is triggered as result of roundabout forming closed way? (or it is actually unrelated....)

**Comment by Phyks** [comment]
Thanks for the digging into osm2pgsql, it is likely this issue. We are running previous Ubuntu LTS with osm2pgsql 1.2.1 while 1.4.1 is available and should have fixed these. We'll have a look.
