### ISSUE TITLE
Ignores the 'disused:' prefix?

### ISSUE THREAD

**Issue by DaveF63** [cyclosm/cyclosm-cartocss-style#626]
Hi 

This bike shop is still rendering even though it is tagged as 'disused:'
Is the tag service:bicycle:retail really usurping other tags as claimed in this changeset comment?

https://www.openstreetmap.org/way/928481652/history#map=19/51.38580/-2.35930

**Comment by Florimondable** [comment]
>  Is the tag service:bicycle:retail really usurping other tags as claimed in this changeset comment?
I’d say yes, may be we should check the main tag, but that’d had some perf cost and difficult to implement.

**Comment by DaveF63** [comment]
Are you saying you don't check for 'shop=bicycle'?
If no, then that's very strange.
If yes, then checking for 'disused:...' prefixes is not really a performance hit.
'disused:' is a commonly used prefix.

**Comment by Phyks** [comment]
It is: https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/views.sql#L200-L202.

If there is an interesting `shop` value, we render it preferentially. Otherwise, we look for alternative tags which could be interesting to render.

1/ We cannot have too much complex logic here, so we assume someone turning a `shop` in `disused:shop` will as well update the less frequent tags as they now have no meaning.
2/ Some shops are on a very different topic as bikes (delis, etc.), but they do offer bike services which is interesting to render.
3/ This render emphasized a tagging issue (not discarding extra tags) which is useful for contributors.
