### ISSUE TITLE
More POI

### ISSUE THREAD

**Issue by Florimondable** [cyclosm/cyclosm-cartocss-style#64]
We need more POI because cyclist like to pedals to go to :
- theatre/spectacle
- movie theatre
- library
- school (from 2yo to university)
- swimming pool icon
- subway station with its name (in high zoom)

**Comment by Culdesac49** [comment]
also street markets (with market days ?), it useful for traveling, but no idea how it's done in OSM

**Comment by Phyks** [comment]
Streets markets would be really nice to have because they have the side effect of blocking some cycle lanes. I'm thinking in https://www.openstreetmap.org/node/1425912333 for instance. Not sure how to render temporal data though, cf #65 (we cannot update the generated images depending on time of the day).

A possibility would be to have an overlay layer, a GeoJSON layer typically, and this one could be temporal easily.

Concerning the POIs, I agree we could definitely use a bit more POIs (in particular swimming pools and publicly accessible buildings). We should take care though not to include too much of them to not clutter the map. If someone needs it to look up a specific POI or plan a route, I guess this should rather rely on the tooling around:

- Looking up a specific POI should probably be done through a search box and put a marker on the map, similary to http://demo.addok.xyz, with a CyclOSM background.
- Planning a route with specific start and end point could be done by BRouter (http://brouter.de/brouter-web/), with a CyclOSM background.

**Comment by sylvainavelo** [comment]
I think there are too many POIs already. Or that bicycle related POIs are not prominent enough compared to others :
* bicycle shops or bicycle rentals are difficult to find, they are dark grey while other POIs have colored symbols (supermarkets, pharmacy, restaurants are more visible)
* a simple colored circle for bicycle parking is not understandable without looking at the legend

**Comment by Phyks** [comment]
> I think there are too many POIs already. Or that bicycle related POIs are not prominent enough compared to others.

This is true. We have multiple POI icons coming from various sources at the moment, and this could definitely use a bit of redesign / homogeneization… :/ Bicycle POIs appear first on the map (we already have a zoom-in prioritization of POIs) but their icon is not visible enough. New POIs mentionned in this issue would only appear at higher zoom levels.

> a simple colored circle for bicycle parking is not understandable without looking at the legend

This is a known issue but this seems acceptable to me. The problem is there are *a lot* of bicycle parkings out there and rendering all of them with a full icon clutter a bit the map (especially when you want capacity in addition). Colored cycle is taken from OpenCycleMap so as to not change too much from the existing renders.

**Comment by Florimondable** [comment]
Yes we need to work on the POI's priorization and at which level to draw them. Bicycle and first aid first !

**Comment by quasart** [comment]
Hello everybody,
when POI are reworked, it could be nice to change train station (icon and label) color, because blue is generally color for bikes

**Comment by Phyks** [comment]
Another use case here. I was going to Darty https://www.openstreetmap.org/node/2194078967. CyclOSM map is completely empty in this commercial area: https://www.cyclosm.org/#map=19/45.64745/-1.05047/cyclosm. Every building look the same and it is very difficult to orient oneself.

More POIs and especially shops could serve multiple roles, first cyclist might want to get there, second they are useful to orient oneself. So we should probably render many more POIs (including not bicycle-related ones) only at very high zoom (Z19 / Z20)?

Additionnally, I think we should render commercial areas with a dedicated background color (see the red osm.org uses https://www.openstreetmap.org/#map=17/45.64652/-1.04756) as even without the proper POI details, these would indicate at low zoom that there is likely a supermarket / shops / first aid / people there.

**Comment by Phyks** [comment]
Going through this 

- [x] theatre/spectacle
- [x] movie theatre
- [x] library
- [ ] <del>school (from 2yo to university)</del>
- [ ] swimming pool icon
- [x] subway station with its name (in high zoom)
- [ ] <del>Darty, see https://www.openstreetmap.org/node/2194078967</del>
- [x] Intermarché see https://www.cyclosm.org/#map=18/49.84017/3.92038/openstreetmap
- [ ] Bricomarché see https://www.cyclosm.org/#map=18/49.84017/3.92038/openstreetmap > `shop=doityourself`

I think we can do without schools and electronic stores such as Darty (the global use case would be improved with #537). 

Swimming pools are useful since it is a place to have a shower + a nice amenity when you are touring with your bike, I'd render them.

Bricomarché / `shop=doityourself` is missing from the render, while you can find tools and useful stuff for your bike there. I'd render them.
