### ISSUE TITLE
cycle track rendered too strongly at zoom 11

### ISSUE THREAD

**Issue by kaneap** [cyclosm/cyclosm-cartocss-style#654]
Cycle tracks (`cycleway=track`) renders significantly thicker than separate cycleways at zoom 11. 

Compare the rendering of these two roads at zoom 16 ![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/35740782/6f45b032-13ae-4982-b8b0-4d9bb3ef2b67) and at zoom 11
![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/35740782/4eabf288-b8a7-4c14-a727-14b24a49f53a)
Example location: https://www.cyclosm.org/#map=16/52.5314/13.5000/cyclosm In this example I circled the road with separate cycleways in red, and with cycle tracks as tag in green.

This doesn't seem to be an issue on cycle tracks on `highway=primary` or `highway=secondary`.

**Comment by Phyks** [comment]
I'm not sure this issue can be easily fixed without adding a lot of overhead in the scripts. 

If the cycle track is mapped separately, it has a definite width. If it is mapped onto the highway, it inherits the width of the casing of the highway. 

Doing otherwise would mean adding a lot of logic. It would also make rendering weird for highways which mix no cycleway and cycle tracks on different segments.
