### ISSUE TITLE
Unnecessary ending dot on node_network labels

### ISSUE THREAD

**Issue by sylvainavelo** [cyclosm/cyclosm-cartocss-style#660]
I spoted a minor issue on the rendering of node networks.

According to the map legend, nodes of a node_network are supposed to be labeled with their number:
![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/14272233/298c7510-8b18-4d77-8c0c-141a8411408f)

But the numbers seem to be always followed by an unnecessary dot, which makes them look a bit "off", not centered: 
![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/14272233/2c4d805f-0153-43fa-9f17-4d784ca6602f)

It may be linked to this part of the code, which concatenates multiple possible references (international, national, regional and local node network) with a dot: 
https://github.com/cyclosm/cyclosm-cartocss-style/blob/c4e8611aca2f5c00d4cb6b73c3e7bc4676e0627c/project.mml#L998-L1002

I don't think I can reproduce the toolchain now to try and submit a PR myself. Kudos to anyone who can!

**Comment by Phyks** [comment]
Hi,

Thanks for the bug report. Indeed, it is coming from [this change](https://github.com/cyclosm/cyclosm-cartocss-style/commit/54eeb411994e1027b7289779cf79fa3eb0be2b04) which aimed at truncating long cycle junction names. Original issue was https://github.com/cyclosm/cyclosm-cartocss-style/issues/381. The dot is now always appended, truncation or not. 

Two options for a fix:
* Either remove the final node, making truncation of the node junction name implicit rather than explicit. This keeps a simple SQL query.
* Or add a check for whether truncation should occur or not and append the final dot only in this case.

**Comment by sylvainavelo** [comment]
The first option, removing the final dot whether a truncation occured or not, seems a perfectly appropriate way to deal with the issue.

----

I didn't get the exact role of this part of the query because I didn't know node refs could be longer than 3 digits.

A quick query for nodes with a ref starting with a letter shows it is quite unusual : https://overpass-turbo.eu/s/1CgJ

And in some places, truncating the ref makes it too short to be relevant. It seems there are two networks which have this issue. In Catalonia there is network with references that are 5 characters long. 

![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/14272233/4bb28873-7782-47f1-b534-c42530a165f4)

The other network is north of Hamburg with nodes containing an abbreviated city name before the number. For instance `Nds140` for a node in the city of Norderstedt.

![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/14272233/ba80c453-e077-4fda-94df-91c29856592f)

In both cases, the end of the ref seems more relevant than the beginning.

Knowing this, wouldnt it be appropriate to make the substring from the end instead of the beginning ?

**Comment by Phyks** [comment]
Done, thanks for the checks!
