### ISSUE TITLE
Slow/Not Loading

### ISSUE THREAD

**Issue by crazyjack123** [cyclosm/cyclosm-cartocss-style#673]
CyclOSM has a slow/not loading. 

![Screenshot 2024-06-03 at 13 24 07](https://github.com/cyclosm/cyclosm-cartocss-style/assets/171570577/647d910e-29fc-41dd-aede-fe2bc1948881)

**Comment by Phyks** [comment]
Thanks for the report, I'll have a look ASAP. I'll try to add more exhaustive monitoring as well on the map.

**Comment by paulcakeface** [comment]
Yeah, having the same issue

**Comment by momentmal** [comment]
Same issue here today.

Doesn't matter if I use the regular URL
`https://a.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png`
or the alternative CyclOSM Live Dev URL
`https://dev.{s}.tile.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png`

Both are loading extremely slow right now

![image](https://github.com/cyclosm/cyclosm-cartocss-style/assets/9054832/e0bd9429-099d-46d1-b0cc-30ccd2f30f2f)

**Comment by Phyks** [comment]
I guess the problem with recent vandalism is that it affects a **huge** number of tiles, at middle zoom levels (around zoom 14, which is very compute-intensive). Therefore, a lot of tiles get re-rendered to handle the vandalism changesets, and they then get cached agressively (because this zoom level is quite aggressively cached, given its computation time).

Therefore, whenever a vandalism wave intervene, the tile server first get overwhelmed by new tiles to render and then cache and serve the faulty tiles for a while :/

I hope this should stabilize now, and should resolve itself with the expiry of the cached tiles in a matter of hours/days. Hope DWG will find something to handle properly this vandalism wave which is happening again and again lately.
