### ISSUE TITLE
Make cycleway:right=track visible from a lower zoom level

### ISSUE THREAD

**Issue by Coehill** [cyclosm/cyclosm-cartocss-style#684]
> Reminder that OSM zoom levels go from 0 (world map) to 20 (very local area).  So a low zoom level is "zoomed out".

StreetComplete adds the following tags when there is a "[sidepath or protected bicycle lane, both directions](https://github.com/user-attachments/assets/e5701268-795f-42de-88e1-1370cb3e83af)" on the right side of the road:

```
cycleway:right=track
cycleway:right:oneway=no
```

However, I am not seeing it rendered on CycleOSM unless I zoom in very closely.  This is one of the better bicycle infrastructure options available, so it is odd that it is not rendered when zoomed out while painted bicycle lanes are.

[Example image of infrastructure](https://panoramax.openstreetmap.fr/images/f6/82/0a/07/2cf3-4bfe-b2c4-964f200c9108.jpg)
![Screenshot from StreetComplete](https://github.com/user-attachments/assets/e5701268-795f-42de-88e1-1370cb3e83af)

If someone can point me in the right direction, I am happy to adjust at what zoom level these tags are rendered.

**Comment by Phyks** [comment]
Hi,

Thanks for the report! Happy to consider a PR for this.

Cycleways are fetched from `osm2pgsql` database in PostgreSQL in the `views.sql` file: https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/views.sql#L81-L116.

Their style is defined in `roads.mss`. Unless I'm mistaken, they should be rendered from Z11 upwards and having 50% larger width since they are not oneway: https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/roads.mss#L833-L848.

**Comment by Coehill** [comment]
Hi @Phyks.  It turns out that a recent edit of mine wasn't displaying on the map and now it consistently shows up from a reasonable zoom level, even when clearing cache.  So this ticket may be closed.
