### ISSUE TITLE
Render state=disused

### ISSUE THREAD

**Issue by NSaik** [cyclosm/cyclosm-cartocss-style#690]
It would be useful to render the "state=disused" tag. CyclOSM currently renders state=proposed as dashed lines, so there's some precedence for using the 'state=' key already.

There are a few routes where I live that existed for many years, but sections of them have recently been retired from the official route map as legacy bikeways. The sections were removed due to being unsafe, so it would be useful if the renderer was able to differentiate the sections labeled with the "state=disused" tag.

**Comment by kaneap** [comment]
Do these routes exist anymore? It not then IMO this sounds a bit like a [trolltag](https://wiki.openstreetmap.org/wiki/Trolltag) in that the bike route doesn't really exist anymore. Usually using a lifecycle tag is better for communicating that a route doesn't exist anymore, e.g. `disused:route=bicycle`.

It looks like `state=disused` is used on 84 bicycle route relations, all but 9 of them in Finland.

**Comment by Phyks** [comment]
Agreed with @kaneap here, I'd rather tag them as `disused:route=bicycle` (and then, they won't be rendered anymore).

I don't see much point in rendering them, since the tagging scheme implies they no longer exist (so not useful for bikers, since there should not be anymore infra on the ground). And given the very light usage of `state=disused` (https://taginfo.openstreetmap.org/tags/state=disused#overview 164 occurrences total worldwide), and not an emerging tag/new tagging scheme, I would not render it.
