### ISSUE TITLE
Show maxspeed of ways

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#7]
The maxspeed of the ways should be rendered somehow, especially in urban area. Typically distinguishing between `maxspeed=FR:urban` (50 km/h) and `maxspeed=FR:30` would be super useful.

Not sure about the best render. Possible idea would be to change the background (fill) color of the street based on `maxspeed`.

**Comment by Phyks** [comment]
```
SELECT
    unit AS initial_unit,
    CASE
        WHEN maxspeed~E'^\\d+$' THEN maxspeed::integer
        WHEN maxspeed~E'^\\d+ mph$' THEN REPLACE(maxspeed, ' mph', '')::integer * 1.609344
        WHEN maxspeed~E'^\\d+ knots$' THEN REPLACE(maxspeed, ' knots', '')::integer * 1.852
        WHEN maxspeed='walk' THEN 5
        ELSE NULL
    END AS kmh_value
    FROM (
        SELECT 'kmh' AS unit, '30' AS maxspeed
        UNION ALL
        SELECT 'mph' AS unit, '30 mph' AS maxspeed
        UNION ALL
        SELECT 'knots' AS unit, '30 knots' AS maxspeed
        UNION ALL
        SELECT 'walk' AS unit, 'walk' AS maxspeed
    ) AS data;
```

Gives

| initial_unit  | kmh_value |
| ------------- | ------------- |
| kmh  | 30  |
| mph  | 48.280320  |
| knots  | 55.560  |
| walk  | 5  |

**Comment by Phyks** [comment]
Added as a `maxspeed_kmh` field for road layers in https://github.com/cyclosm/cyclosm-cartocss-style/commit/4303f929a45c6281bb2407c5000a23c9448a8849.

**Comment by Florimondable** [comment]
My idea is to render the fill of the road in blue cyan when the road is 30km/h or under
30km/h would be light cyan, <20 (living streets) darker cyan, (<10) pedestrian darker darker cyan.

I don't think it's usefull to distinguish speed over 30, because if it is over 80km/h it must be a road where bike is forbidden (hence the road is drawn in grey-green as motorway), if you are in town it certainly be <50km/h and in country between 50 and 80. So you already know the default speed of a road.

**Comment by Phyks** [comment]
#67 is kind of related as well btw.

**Comment by Phyks** [comment]
Very nicely done by @Florimondable in #71, closing this.
