### ISSUE TITLE
Render cycle ways with direction

### ISSUE THREAD

**Issue by Phyks** [cyclosm/cyclosm-cartocss-style#8]
Cycle ways / lanes / tracks should be rendered with an indication of their direction. Typically, https://tiles.phyks.me/#17/48.82218/2.33203 is not very clear as to which cycle way is in the direction of the traffic and which one is contraflow.

![1](https://user-images.githubusercontent.com/3856586/51792864-d521ba80-21b7-11e9-8b0f-10b435661528.png)

- [ ] Render directions of cycle ways.
- [ ] Render directions of cycle routes (through the backward / forward members)

**Comment by Culdesac49** [comment]
on oneway, bicycle opposite lane or opposite track should only be show on the right side of the street (in France at least), even if the OSM data does not precise the side of the track/lane. If not, it will let us think that there is a lane or a track on both side of the street.

**Comment by Florimondable** [comment]
I don't think it is necessary to draw the direction of lane/track/busway on a side a of a street. Because almost all the time it on the side where people drive (right in France).
Though it is necessary to draw oneway (or maybe only twoway) on highway=cycleway.

Opposite_lane should not be drawn by default on the right side because
- that depends of the country and that must be hard to know on which side people drive
- it helps contributors to precise the osm data, we must set cycleway:left/right=opposite_lane, cycleway=opposite_lane is not a precise enough.

**Comment by Florimondable** [comment]
done by #94
