### ISSUE TITLE
[Suggestion] Hide buildings

### ISSUE THREAD

**Issue by Shohreh** [cyclosm/cyclosm-cartocss-style#80]
Hello,

Thumbs up for the project!

I have a suggestion, which could simply be a user-specified option: Make it possible to _hide_ buildings. They make maps harder to read, and are useless most of the time anyway.

Here's an example:
https://media.giphy.com/media/oHxvMekWBSFYLDFf7w/giphy.gif

Cheers, # #

**Comment by Florimondable** [comment]
User specific option is hard to do with .png generated images ;)
I think building is usefull to locate yourself or to find something.
Though we've already remove the fake building 3D effect, I'm considering fading more the building when we'll add the elevation curves in order to make them readable in town.

**Comment by Florimondable** [comment]
Building is now shown only from zoom 16.
